### ISSUE TITLE
time allocation

### ISSUE THREAD

**Issue by tiralonghipol** [ZJU-FAST-Lab/large_scale_traj_optimizer#1]
very nice work!

can you explain / point to a resource regarding the choice of the time allocation for each piece?
I refer to the allocateTime function

thanks!

**Comment by ZhepeiWang** [comment]
Via the function "Eigen::VectorXd getGradT(void)", you can obtain analytical gradient w.r.t time allocation. This means you can directly optimize the time allocation using some external optimizers. You can simply set all time durations to 0.01, then let the optimizer do the rest.

**Comment by tiralonghipol** [comment]
@ZhepeiWang  I refer to this specific function you wrote in the example
https://github.com/ZJU-FAST-Lab/large_scale_traj_optimizer/blob/aadf8e67ce86e7ad448ed6a09c5300a3a3ed99df/example1/src/example1_node.cpp#L45

**Comment by ZhepeiWang** [comment]
This functions implements the _trapezoidal velocity profiles_. The duration from p1 to p2 is determined by static->acceleration->max_vel->deceleration->static along a straight path. Every piece duration can be initialized as above for optimization.

**Comment by ZhepeiWang** [comment]
By the way, trapezoidal velocity profiles produce conservative time allocation. It cannot be used directly without further optimization.

**Comment by tejalbarnwal** [comment]
Hi @ZhepeiWang ,

As you mentioned above, the  `allocateTime` function uses trapezoidal velocity profile to generate the duration from p1 to p2.
I wanted to confirm a small query(might be silly) inside the same for the following particular case,
https://github.com/ZJU-FAST-Lab/large_scale_traj_optimizer/blob/aadf8e67ce86e7ad448ed6a09c5300a3a3ed99df/example1/src/example1_node.cpp#L67-L72

When `(D < accd + dccd)`, the velocity profile doesn't reach the velocity of `vel` and therefore the achieved velocity would be a lesser than `vel`. So, assuming the initial and final velocity is zero, as you did [here](https://github.com/ZJU-FAST-Lab/large_scale_traj_optimizer/blob/aadf8e67ce86e7ad448ed6a09c5300a3a3ed99df/example1/src/example1_node.cpp#L62-L65) to derive `acct` and `dcct`, shouldn't the equations be,
```
t1 = sqrt(2 * acc * D) / acc;
t2 = (acc * t1) / acc;
dtxyz = t1 + t2;
```

Please confirm if I am missing something
Thank you for your help!

**Comment by tejalbarnwal** [comment]
> Via the function "Eigen::VectorXd getGradT(void)", you can obtain analytical gradient w.r.t time allocation. This means you can directly optimize the time allocation using some external optimizers. You can simply set all time durations to 0.01, then let the optimizer do the rest.

Hi @ZhepeiWang ,
Thank you for your work. Could you please please elaborate more on the point you mentioned above.about using external optimizer to optimize the time allocation
