### ISSUE TITLE
Using the optimizer for solving trajectory between only two states

### ISSUE THREAD

**Issue by MihirDharmadhikari** [ZJU-FAST-Lab/large_scale_traj_optimizer#2]
Hello,

Thank you for this software!
I wanted to ask how can this package be used to generate trajectories between only two states without having any waypoints in between. Looking at the code I found that the problem formulation for the optimization requires at least one waypoint in between the start and end state. Please correct me if I am missing anything.

Best,
Mihir

**Comment by ZhepeiWang** [comment]
Yes, you are right. In this repo, I do not consider the case when only one piece is needed. In general, a single-piece trajectory lacks degrees of freedom (DoFs) for optimization. But it also depends on what the trajectory is used for.

A single-piece trajectory is fully determined by its scalar duration T and two boundaries. If all these constants are given, the constructor "Piece(BoundaryCond bdCond, double dur)" may help you to compute such a piece.

**Comment by MihirDharmadhikari** [comment]
Hello @ZhepeiWang 

Thank you for your reply. I will try the above approach and see how it works.

Best,
Mihir
