### ISSUE TITLE
Oscillating Generated Trajectory

### ISSUE THREAD

**Issue by marios-stam** [ZJU-FAST-Lab/large_scale_traj_optimizer#3]
Hello and thank you for your work. I am trying to use your code to generate trajectories through waypoints, but   I often receive these unexpected results. The green line is the path of waypoints I want to follow and the blue line is the generated trajectory

Thank you in advance!

![image](https://user-images.githubusercontent.com/37310507/167914711-cd144e15-e067-470b-9971-ad68b008e657.png)
![image](https://user-images.githubusercontent.com/37310507/167914800-3619ac49-60bf-4305-ad62-5bf886294001.png)

**Comment by ZhepeiWang** [comment]
Have you ever set a proper a time allocation or optimize them for each piece? 
This repo only provides a differentiable trajectory generator which cannot be used along without a 
high-level optimizer.
