### ISSUE TITLE
about the obstacles avoidance

### ISSUE THREAD

**Issue by feiyuxiaoThu** [ZJU-FAST-Lab/large_scale_traj_optimizer#4]
Thanks for open-sourcing this nice work, and I have a small question:
The corridor generation and usage for obstacle avoidance part mentioned in your paper seems not to be included in this repo, how can
I learn about the details about those parts?

**Comment by ZhepeiWang** [comment]
Sorry for the late reply since I have been at a full time job. The other parts in my paper has been outdated. If you are intereted in these topics. It will be better to check this repo [https://github.com/ZJU-FAST-Lab/GCOPTER].
