### ISSUE TITLE
Incorrect gradient w.r.t time allocation in minimum snap trajectory

### ISSUE THREAD

**Issue by sritank** [ZJU-FAST-Lab/large_scale_traj_optimizer#5]
Great work and I appreciate you making this planner available to the community.

There is a bug in the code when calculating the gradient w.r.t. time for the minimum snap trajectory. The SnapOpt::getGradT() function gives incorrect gradient values. All of the equations from the ICRA paper have been computed correctly except for one term:
Specifically line 1113 in file `include/traj_min_snap.hpp`. 

It is missing a negative sign
`coeffsGradT(5) = 604800.0 * ((iV + fV) * (iP - fP)).sum();`

should be:
`coeffsGradT(5) = -604800.0 * ((iV + fV) * (iP - fP)).sum();`

I also verified the above by writing my own minimum snap solver and calculating the numerical gradient.

I didn't have time to verify the other gradient calculations like getGradInnerP(), etc. but analytically they seem correct.

**Comment by ZhepeiWang** [comment]
Thank you Mr.Sritank! I have check the code and find that I did miss a negative sign on line 1113. Your correction can also be validated by line 830. I will merge your PR. Good job!

**Comment by ZhepeiWang** [comment]
Fixed by Mr. Sritank! Thus closed here.
